### ISSUE TITLE
Rename the project (terraform-packet-openstack)

### ISSUE THREAD

**Issue by jmarhee** [equinix/terraform-metal-openstack#45]
In order to submit this to the Terraform Registry, we'll need to rename the project to something like terraform-packet-openstack.

https://metal.canny.io/integrations/p/openstack-terraform-module

**Comment by displague** [comment]
If we can perform this rename just after https://github.com/packethost/terraform-provider-packet/pull/288, we can have one less hop and go with `equinix/terraform-equinix-metal-openstack`

**Comment by displague** [comment]
We would want to ensure that this is the proper home for this module.

I am excited to see both providers and several modules listed on the https://registry.terraform.io/namespaces/equinix page.

**Comment by displague** [comment]
The name would be `equinix/terraform-metal-openstack` because the hyphenated provider name caused problems.
